import { PrivateLeasing, MileageAndCost, FuelType } from "./private-leasing.model";

export const PRIVATE_LEASING_OFFERS: PrivateLeasing[] = [
    new PrivateLeasing(
        'Volkswagen',
        'Golf',
        'Standard',
        3995,
        FuelType.Petrol,
        36,
        1000,
        [new MileageAndCost(1500, 215), new MileageAndCost(2000, 595)],
        true,
        352,
        450,
        'https://privatleasing.volkswagen.se/'
    ),
    new PrivateLeasing(
        'Volkswagen',
        'ID.4',
        'Standard',
        4995,
        FuelType.Electric,
        36,
        1000,
        [new MileageAndCost(1500, 350), new MileageAndCost(2000, 690)],
        true,
        534,
        700,
        'https://privatleasing.volkswagen.se/'
    ),
    new PrivateLeasing(
        'Volvo',
        'EX30',
        'Standard',
        3995,
        FuelType.Electric,
        36,
        1000,
        [new MileageAndCost(1500, 190), new MileageAndCost(2000, 471)],
        true,
        335,
        780,
        'https://www.volvocars.com/se/privatleasing'
    ),
    new PrivateLeasing(
        'Volvo',
        'EX40',
        'Standard',
        4995,
        FuelType.Electric,
        36,
        1000,
        [new MileageAndCost(1500, 241), new MileageAndCost(2000, 573)],
        true,
        290,
        792,
        'https://www.volvocars.com/se/privatleasing'
    ),
    new PrivateLeasing(
        'Toyota',
        'Yaris Cross 1.5',
        'Standard',
        3195,
        FuelType.Hybrid,
        36,
        1500,
        [new MileageAndCost(2000, 319), new MileageAndCost(2500, 558)],
        true,
        311,
        464,
        'https://easyprivatleasing.toyota.se/'
    ),
    new PrivateLeasing(
        'Toyota',
        'Corolla TS',
        'Standard',
        3395,
        FuelType.Hybrid,
        36,
        1500,
        [new MileageAndCost(2000, 315), new MileageAndCost(2500, 560)],
        true,
        320,
        516,
        'https://easyprivatleasing.toyota.se/'
    ),
    new PrivateLeasing(
        'Tesla',
        'Model 3',
        'Standard',
        5319,
        FuelType.Electric,
        36,
        1000,
        [new MileageAndCost(1500, 232), new MileageAndCost(2000, 521)],
        false,
        500,
        Math.floor(19979 / 36),
        'https://www.tesla.com/sv_SE/model3'
    ),
    new PrivateLeasing(
        'Tesla',
        'Model Y',
        'Standard',
        7481,
        FuelType.Electric,
        36,
        1000,
        [new MileageAndCost(1500, 257), new MileageAndCost(2000, 578)],
        false,
        1500,
        27000 / 36,
        'https://www.tesla.com/sv_se/modely/'
    ),
    new PrivateLeasing(
        'Audi',
        'A3',
        'Standard',
        3495,
        FuelType.Petrol,
        36,
        1000,
        [new MileageAndCost(1500, 270), new MileageAndCost(2000, 570)],
        true,
        394,
        515,
        'https://privatleasing.audi.se/'
    ),
    new PrivateLeasing(
        'Audi',
        'Q4',
        'Standard',
        5895,
        FuelType.Electric,
        36,
        1000,
        [new MileageAndCost(1500, 370), new MileageAndCost(2000, 720)],
        true,
        526,
        745,
        'https://privatleasing.audi.se/'
    ),
    new PrivateLeasing(
        'Skoda',
        'Octavia',
        'Standard',
        3490,
        FuelType.Petrol,
        36,
        1000,
        [new MileageAndCost(1500, 240), new MileageAndCost(2000, 630)],
        true,
        293,
        425,
        'https://privatleasing.skoda.se/'
    ),
    new PrivateLeasing(
        'Skoda',
        'Karoq',
        'Standard',
        3595,
        FuelType.Petrol,
        36,
        1000,
        [new MileageAndCost(1500, 240), new MileageAndCost(2000, 645)],
        true,
        334,
        495,
        'https://privatleasing.skoda.se/'
    ),
    new PrivateLeasing(
        'Citroën',
        'C3',
        'Standard',
        3195,
        FuelType.Petrol,
        36,
        1000,
        [new MileageAndCost(1500, 240), new MileageAndCost(2000, 645)],
        true,
        334,
        495,
        'https://privatleasing.citroen.se/'
    ),
    new PrivateLeasing(
        'Citroën',
        'C4',
        'Standard',
        3795,
        FuelType.Petrol,
        36,
        1000,
        [new MileageAndCost(1500, 240), new MileageAndCost(2000, 645)],
        true,
        334,
        495,
        'https://privatleasing.citroen.se/'
    )
];