import { PrivateLeasing, FuelType } from "./private-leasing.model";

export const PRIVATE_LEASING_OFFERS: PrivateLeasing[] = [
    new PrivateLeasing(
        'Volkswagen',
        'Golf',
        'Standard',
        3995,
        FuelType.Petrol,
        36,
        1000,
        0,
        352,
        450,
        'https://privatleasing.volkswagen.se/',
        null,
        223
    ),
    new PrivateLeasing(
        'Volkswagen',
        'ID.4',
        'Standard',
        4995,
        FuelType.Electric,
        36,
        1000,
        0,
        534,
        700,
        'https://privatleasing.volkswagen.se/',
        null,
        876
    ),
    new PrivateLeasing(
        'Volvo',
        'EX30',
        'Standard',
        3995,
        FuelType.Electric,
        36,
        1000,
        0,
        335,
        780,
        'https://www.volvocars.com/se/privatleasing',
        null,
        67
    ),
    new PrivateLeasing(
        'Volvo',
        'EX40',
        'Standard',
        4995,
        FuelType.Electric,
        36,
        1000,
        0,
        290,
        792,
        'https://www.volvocars.com/se/privatleasing',
        null,
        222
    ),
    new PrivateLeasing(
        'Toyota',
        'Yaris Cross 1.5',
        'Standard',
        3195,
        FuelType.Hybrid,
        36,
        1500,
        0,
        311,
        464,
        'https://easyprivatleasing.toyota.se/',
        null,
        122
    ),
    new PrivateLeasing(
        'Toyota',
        'Corolla TS',
        'Standard',
        3395,
        FuelType.Hybrid,
        36,
        1500,
        0,
        320,
        516,
        'https://easyprivatleasing.toyota.se/',
        null,
        897
    ),
    new PrivateLeasing(
        'Tesla',
        'Model 3',
        'Standard',
        5319,
        FuelType.Electric,
        36,
        1000,
        200,
        500,
        Math.floor(19979 / 36),
        'https://www.tesla.com/sv_SE/model3',
        null,
        333
    ),
    new PrivateLeasing(
        'Tesla',
        'Model Y',
        'Standard',
        7481,
        FuelType.Electric,
        36,
        1000,
        200,
        1500,
        27000 / 36,
        'https://www.tesla.com/sv_se/modely/',
        null,
        254
    ),
    new PrivateLeasing(
        'Audi',
        'A3',
        'Standard',
        3495,
        FuelType.Petrol,
        36,
        1000,
        0,
        394,
        515,
        'https://privatleasing.audi.se/',
        null,
        1275
    ),
    new PrivateLeasing(
        'Audi',
        'Q4',
        'Standard',
        5895,
        FuelType.Electric,
        36,
        1000,
        0,
        526,
        745,
        'https://privatleasing.audi.se/',
        null,
        127
    ),
    new PrivateLeasing(
        'Skoda',
        'Octavia',
        'Standard',
        3490,
        FuelType.Petrol,
        36,
        1000,
        0,
        293,
        425,
        'https://privatleasing.skoda.se/',
        null,
        1275
    ),
    new PrivateLeasing(
        'Skoda',
        'Karoq',
        'Standard',
        3595,
        FuelType.Petrol,
        36,
        1000,
        0,
        334,
        495,
        'https://privatleasing.skoda.se/',
        null,
        600
    ),
    new PrivateLeasing(
        'Citroën',
        'C3',
        'Standard',
        3195,
        FuelType.Petrol,
        36,
        1000,
        0,
        334,
        495,
        'https://privatleasing.citroen.se/',
        null,
        500
    ),
    new PrivateLeasing(
        'Citroën',
        'C4',
        'Standard',
        3795,
        FuelType.Petrol,
        36,
        1000,
        0,
        334,
        495,
        'https://privatleasing.citroen.se/',
        null,
        200
    )
];